version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    executor:
      name: win/default
    steps:
      # default shell is Powershell
      - run:
         command: dir
         shell: cmd.exe
      - run:
         command: dotnet test
         shell: cmd.exe
